export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMUALRIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMUALRIO_ERROR = 'VALIDAR_FORMUALRIO_ERROR';

export const AGREGAR_ESTABLECIMIENTO = 'AGREGAR_ESTABLECIMIENTO';
export const AGREGAR_ESTABLECIMIENTO_EXITO = 'AGREGAR_ESTABLECIMIENTO_EXITO';
export const AGREGAR_ESTABLECIMIENTO_ERROR = 'AGREGAR_ESTABLECIMIENTO_ERROR';

export const AGREGAR_CADENA = 'AGREGAR_CADENA';
export const AGREGAR_CADENA_EXITO = 'AGREGAR_CADENA_EXITO';
export const AGREGAR_CADENA_ERROR = 'AGREGAR_CADENA_ERROR';
